// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMypui6W5KOHax8zK9cv0Fo7jgEqqog64',
    appId: '1:608904546667:web:2f9eff6b693f243b4b242e',
    messagingSenderId: '608904546667',
    projectId: 'auth-264bf',
    authDomain: 'auth-264bf.firebaseapp.com',
    storageBucket: 'auth-264bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrAW8p7xYwbHw9akNkN8bKVmtiUUUEyVI',
    appId: '1:608904546667:android:0ee0f0e797acfa764b242e',
    messagingSenderId: '608904546667',
    projectId: 'auth-264bf',
    storageBucket: 'auth-264bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdFSM___mPYKp4qfV9Ak-SN-u6fGNyv-o',
    appId: '1:608904546667:ios:a06cfb11988a2d7e4b242e',
    messagingSenderId: '608904546667',
    projectId: 'auth-264bf',
    storageBucket: 'auth-264bf.appspot.com',
    iosBundleId: 'com.example.aunticacionGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdFSM___mPYKp4qfV9Ak-SN-u6fGNyv-o',
    appId: '1:608904546667:ios:cbe477ba4d7142374b242e',
    messagingSenderId: '608904546667',
    projectId: 'auth-264bf',
    storageBucket: 'auth-264bf.appspot.com',
    iosBundleId: 'com.example.aunticacionGoogle.RunnerTests',
  );
}
